### ISSUE TITLE
NPE when clients connect before the WebSocket servers come online

### ISSUE THREAD

**Issue by Lonor** [Lonor/websocket-cluster#2]
### 问题
在 WebSocket 实例启动之前，创建几个客户端，这些客户端总是周期性地不断尝试重连。此时再启动 WebSocket 服务，抛出如下异常。

### 现象

```logs
org.springframework.data.redis.listener.adapter.RedisListenerExecutionFailedException: Listener method 'handleMessage' threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.data.redis.listener.adapter.MessageListenerAdapter.invokeListenerMethod(MessageListenerAdapter.java:377) ~[spring-data-redis-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.data.redis.listener.adapter.MessageListenerAdapter.onMessage(MessageListenerAdapter.java:308) ~[spring-data-redis-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.data.redis.listener.RedisMessageListenerContainer.executeListener(RedisMessageListenerContainer.java:250) [spring-data-redis-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.data.redis.listener.RedisMessageListenerContainer.processMessage(RedisMessageListenerContainer.java:240) [spring-data-redis-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.data.redis.listener.RedisMessageListenerContainer.lambda$dispatchMessage$0(RedisMessageListenerContainer.java:987) [spring-data-redis-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
Caused by: java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[na:1.8.0_212]
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[na:1.8.0_212]
        at me.lawrenceli.gateway.server.RedisSubscriber.handleMessage(RedisSubscriber.java:79) ~[classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
        at org.springframework.data.redis.listener.adapter.MessageListenerAdapter$MethodInvoker.invoke(MessageListenerAdapter.java:142) ~[spring-data-redis-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        at org.springframework.data.redis.listener.adapter.MessageListenerAdapter.invokeListenerMethod(MessageListenerAdapter.java:371) ~[spring-data-redis-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
        ... 5 common frames omitted
```

### 原因分析
在此哈希路由方法中，若哈希环是空的，如论被路由的值是什么，总会返回一个空的节点（也就是作为物理服务的真实节点）:
https://github.com/Lonor/websocket-cluster/blob/1f167c4306587b6a9696be1ae656b7358bfa0e3e/common/src/main/java/me/lawrenceli/hashring/ConsistentHashRouter.java#L54-L57

有两处调用：
1. 网关 LB Filter
2. 实例上线时的消息消费，比较节点上线后同一 userId 的不同真实节点，即：

https://github.com/Lonor/websocket-cluster/blob/1f167c4306587b6a9696be1ae656b7358bfa0e3e/gateway/src/main/java/me/lawrenceli/gateway/server/RedisSubscriber.java#L73-L80

而只是遍历中的 `oldServiceNode` 始终是 `null`.

**Comment by Lonor** [comment]
After local testing, I'll make a pull request to fix this.

/label bug

**Comment by Lonor** [comment]
已解决：

https://github.com/Lonor/websocket-cluster/blob/ada67a2a06a12c0b11966bee879bbc72faf4e2c0/gateway/src/main/java/me/lawrenceli/gateway/server/RedisSubscriber.java#L79-L83
